name: test

on:
  workflow_dispatch:

concurrency:
  group: oneatatimeplz

jobs:
  do:
    runs-on: ubuntu-latest
    steps:
      - name: green
        run: |
          set -euxo pipefail
          sleep 30
          echo "Success"
